name: bulid
on:
  push:
  workflow_dispatch:
  schedule:
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
    # This example triggers the workflow every day at 19:00 UTC(JST+0900 04:00, Note: 19+9-24=4):
    - cron:  '0 19 * * *'

env:
  NOPAUSE: 1
  REMOVE_TMP: 1
  RETENTION_DAYS: 3

jobs:
  build-teraterm:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          key: ttssh2-cache
          path: |
            ttssh2/libs
            ttssh2/buildtools
      - name: checkout
        shell: cmd
        run: svn checkout http://svn.osdn.net/svnroot/ttssh2/trunk "ttssh2" --quiet

      - name: show svn rev
        shell: cmd
        working-directory: ttssh2
        run: svn info --show-item revision

      - name: install
        shell: cmd
        run: |
          cd ttssh2\buildtools
          cmake -P install_cygwin.cmake
          cmake -P install_innosetup.cmake
      - name: build
        shell: cmd
        run: |
          cd ttssh2\installer
          release.bat 2
      - name: artifacts_installer
        uses: actions/upload-artifact@v2
        with:
          name: artifacts_installer
          path: ./ttssh2/installer/Output/*.exe
          retention-days: ${{env.RETENTION_DAYS}}
          if-no-files-found: error

      - name: artifacts_zip
        uses: actions/upload-artifact@v2
        with:
          name: artifacts_zip
          path: ./ttssh2/installer/Output/*-snapshot.zip
          retention-days: ${{env.RETENTION_DAYS}}
          if-no-files-found: error

      - name: artifacts_pdb_zip
        uses: actions/upload-artifact@v2
        with:
          name: artifacts_pdb_zip
          path: ./ttssh2/installer/Output/*-snapshot_pdb.zip
          retention-days: ${{env.RETENTION_DAYS}}
          if-no-files-found: error
